#!/bin/bash

# ===============================================================================
# A shell script for automating development with python using virtual environment
# ===============================================================================

if [ -n "$1" ]; then
    case "$1" in
        create-app)
            if [ -n "$2" ]; then
                mkdir "$2" &&
                cd "$2/" &&
                python3 -m venv env &&
                source env/bin/activate &&
                pip install autopep8 &&
                pip freeze > requirements.txt &&
                touch app.py &&
                touch .gitignore &&
                mkdir src &&
                cd src &&
                touch __init__.py &&
                echo
                echo "You have ceated an app!";
            else 
                echo "No project created";
            fi;;
        install)
            if [ -n "$2" ]; then
                source env/bin/activate &&
                pip install "$2" &&
                pip freeze > requirements.txt             
            else
                source env/bin/activate &&
            	pip install -r requirements.txt;
            fi;;
            uninstall)
            if [ -n "$2" ]; then
                source env/bin/activate &&
                pip uninstall "$2" &&
                pip freeze > requirements.txt             
            else
                echo "Nothing to uninstall"
            fi;;
        run)
            if [ -n "$2" ]; then
                source env/bin/activate &&
                python3 "$2";
            else 
                source env/bin/activate &&
                python3 app.py;
            fi;;
        *) echo "Invalid options" ;;
    esac
else
    source env/bin/activate &&
	pip install -r requirements.txt;
fi
